[2024-12-03T13:15:43.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T13:15:43.586+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_dag.calculate_user_location_sales manual__2024-12-03T13:15:35.226037+00:00 [queued]>
[2024-12-03T13:15:43.608+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_dag.calculate_user_location_sales manual__2024-12-03T13:15:35.226037+00:00 [queued]>
[2024-12-03T13:15:43.609+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-03T13:15:43.640+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): calculate_user_location_sales> on 2024-12-03 13:15:35.226037+00:00
[2024-12-03T13:15:43.651+0000] {standard_task_runner.py:63} INFO - Started process 5083 to run task
[2024-12-03T13:15:43.660+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_process_dag', 'calculate_user_location_sales', 'manual__2024-12-03T13:15:35.226037+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/etl_sales.py', '--cfg-path', '/tmp/tmp1oaw44tx']
[2024-12-03T13:15:43.664+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask calculate_user_location_sales
[2024-12-03T13:15:43.750+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_process_dag.calculate_user_location_sales manual__2024-12-03T13:15:35.226037+00:00 [running]> on host a6f8f8b1d92d
[2024-12-03T13:15:44.143+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='k.norasit' AIRFLOW_CTX_DAG_ID='etl_process_dag' AIRFLOW_CTX_TASK_ID='calculate_user_location_sales' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T13:15:35.226037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T13:15:35.226037+00:00'
[2024-12-03T13:15:44.146+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T13:15:44.177+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO user_location_sales (location, gender, total_sales, min_sales, max_sales, average_sales)
        SELECT ui.location, ui.gender, SUM(t.quantity * t.amount),
               MIN(t.quantity * t.amount), MAX(t.quantity * t.amount), AVG(t.quantity * t.amount)
        FROM transaction t
        JOIN user_info ui ON t.user_id = ui.user_id
        GROUP BY ui.location, ui.gender;
        
[2024-12-03T13:15:44.190+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-12-03T13:15:44.202+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-12-03T13:15:44.225+0000] {sql.py:457} INFO - Running statement: 
        INSERT INTO user_location_sales (location, gender, total_sales, min_sales, max_sales, average_sales)
        SELECT ui.location, ui.gender, SUM(t.quantity * t.amount),
               MIN(t.quantity * t.amount), MAX(t.quantity * t.amount), AVG(t.quantity * t.amount)
        FROM transaction t
        JOIN user_info ui ON t.user_id = ui.user_id
        GROUP BY ui.location, ui.gender;
        , parameters: None
[2024-12-03T13:15:44.227+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T13:15:44.228+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: operator does not exist: text = bigint
LINE 6:         JOIN user_info ui ON t.user_id = ui.user_id
                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2024-12-03T13:15:44.241+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_process_dag, task_id=calculate_user_location_sales, execution_date=20241203T131535, start_date=20241203T131543, end_date=20241203T131544
[2024-12-03T13:15:44.264+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task calculate_user_location_sales (operator does not exist: text = bigint
LINE 6:         JOIN user_info ui ON t.user_id = ui.user_id
                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 5083)
[2024-12-03T13:15:44.316+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-03T13:15:44.340+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T13:15:44.341+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
