[2024-12-03T12:25:55.427+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T12:25:55.463+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_dag.load_user_info_data manual__2024-12-03T12:25:50.317103+00:00 [queued]>
[2024-12-03T12:25:55.473+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_dag.load_user_info_data manual__2024-12-03T12:25:50.317103+00:00 [queued]>
[2024-12-03T12:25:55.474+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-12-03T12:25:55.487+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_user_info_data> on 2024-12-03 12:25:50.317103+00:00
[2024-12-03T12:25:55.493+0000] {standard_task_runner.py:63} INFO - Started process 2586 to run task
[2024-12-03T12:25:55.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_process_dag', 'load_user_info_data', 'manual__2024-12-03T12:25:50.317103+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_sales.py', '--cfg-path', '/tmp/tmpz09mx5nx']
[2024-12-03T12:25:55.499+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask load_user_info_data
[2024-12-03T12:25:55.552+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_process_dag.load_user_info_data manual__2024-12-03T12:25:50.317103+00:00 [running]> on host a6f8f8b1d92d
[2024-12-03T12:25:55.803+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='k.norasit' AIRFLOW_CTX_DAG_ID='etl_process_dag' AIRFLOW_CTX_TASK_ID='load_user_info_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T12:25:50.317103+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T12:25:50.317103+00:00'
[2024-12-03T12:25:55.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T12:25:56.024+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T12:25:56.024+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_sales.py", line 27, in load_data_from_minio_to_postgres
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2024-12-03T12:25:56.033+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_process_dag, task_id=load_user_info_data, execution_date=20241203T122550, start_date=20241203T122555, end_date=20241203T122556
[2024-12-03T12:25:56.044+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task load_user_info_data (An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.; 2586)
[2024-12-03T12:25:56.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-03T12:25:56.081+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-12-03T12:25:56.096+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T12:25:56.097+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
